language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - cd Frontend/view
  - npm install
script:
  - npm run build
  - npm run test:unit